[package]
name = "libbfio-rs"
version = "0.1.0"
authors = ["Omer Ben-Amram <omerbenamram@gmail.com>"]
edition = "2018"

[dependencies]
libbfio-sys = {path = "../libbfio-sys"}
libyal-rs-common = {path = "../common"}
chrono = "0.4.6"
time = "0.1.42"
log = "0.4.6"
failure = "0.1.5"
