[package]
name = "libbfio-sys"
description = "Rust bindings for libbfio (https://github.com/libyal/libbfio)"
homepage = "https://github.com/omerbenamram/libbfio-sys"
repository = "https://github.com/omerbenamram/libbfio-sys"
license = "LGPL-3.0+"

readme = "README.md"
version = "0.1.3"
authors = ["Omer Ben-Amram <omerbenamram@gmail.com>"]
edition = "2018"
links = "libbfio"

[build-dependencies]
failure = "0.1.5"
bindgen = "*"

[features]

default = []

# Use when building static bindings
# it's possible to define LIBBFIO_STATIC_LIBPATH to build against local checkout of the library.
static_link = []